groups:
- name: application.rules
  rules:
  # General Application Health
  - alert: ApplicationDown
    expr: up{job=~".*"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Application is down"
      description: "Application {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute."

  - alert: ApplicationHighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Application has high error rate"
      description: "Application {{ $labels.job }} on {{ $labels.instance }} has error rate above 10% for more than 5 minutes."

  - alert: ApplicationHighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Application has high response time"
      description: "Application {{ $labels.job }} on {{ $labels.instance }} has 95th percentile response time above 1 second for more than 5 minutes."

  # MinIO Specific
  - alert: MinIODown
    expr: up{job="minio"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "MinIO is down"
      description: "MinIO instance {{ $labels.instance }} has been down for more than 1 minute."

  - alert: MinIOHighCPU
    expr: rate(container_cpu_usage_seconds_total{container="minio"}[5m]) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MinIO has high CPU usage"
      description: "MinIO instance {{ $labels.instance }} CPU usage is above 80% for more than 5 minutes."

  - alert: MinIOHighMemory
    expr: container_memory_usage_bytes{container="minio"} / container_spec_memory_limit_bytes > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MinIO has high memory usage"
      description: "MinIO instance {{ $labels.instance }} memory usage is above 80% for more than 5 minutes."

  - alert: MinIOStorageFull
    expr: minio_disk_usage_percentage > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MinIO storage is almost full"
      description: "MinIO instance {{ $labels.instance }} storage usage is above 80% for more than 5 minutes."

  # PostgreSQL Specific
  - alert: PostgreSQLDown
    expr: up{job="postgres"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "PostgreSQL is down"
      description: "PostgreSQL instance {{ $labels.instance }} has been down for more than 1 minute."

  - alert: PostgreSQLHighConnections
    expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL has high connection usage"
      description: "PostgreSQL instance {{ $labels.instance }} connection usage is above 80% for more than 5 minutes."

  - alert: PostgreSQLSlowQueries
    expr: rate(pg_stat_database_tup_returned[5m]) / rate(pg_stat_database_tup_fetched[5m]) < 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL has slow queries"
      description: "PostgreSQL instance {{ $labels.instance }} has slow query performance for more than 5 minutes."

  # Node Exporter
  - alert: NodeExporterDown
    expr: up{job="node-exporter"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Node Exporter is down"
      description: "Node Exporter on {{ $labels.instance }} has been down for more than 1 minute."

  - alert: NodeHighLoad
    expr: node_load1 > 4
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Node has high load"
      description: "Node {{ $labels.instance }} has load average above 4 for more than 5 minutes."

  - alert: NodeDiskSpaceLow
    expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Node has low disk space"
      description: "Node {{ $labels.instance }} disk usage is above 80% for more than 5 minutes."

  # cAdvisor
  - alert: ContainerHighCPU
    expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container has high CPU usage"
      description: "Container {{ $labels.name }} on {{ $labels.instance }} has CPU usage above 80% for more than 5 minutes."

  - alert: ContainerHighMemory
    expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container has high memory usage"
      description: "Container {{ $labels.name }} on {{ $labels.instance }} has memory usage above 80% for more than 5 minutes."

  - alert: ContainerRestarting
    expr: rate(container_start_time_seconds[5m]) > 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Container is restarting frequently"
      description: "Container {{ $labels.name }} on {{ $labels.instance }} is restarting frequently."
