groups:
- name: kubernetes.rules
  rules:
  # Kubernetes API Server
  - alert: KubernetesAPIServerDown
    expr: up{job="kubernetes-apiservers"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Kubernetes API Server is down"
      description: "Kubernetes API Server has been down for more than 1 minute."

  # Kubernetes Nodes
  - alert: KubernetesNodeDown
    expr: up{job="kubernetes-nodes"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Kubernetes node is down"
      description: "Kubernetes node {{ $labels.instance }} has been down for more than 5 minutes."

  - alert: KubernetesNodeHighCPU
    expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Kubernetes node has high CPU usage"
      description: "Kubernetes node {{ $labels.instance }} CPU usage is above 80% for more than 5 minutes."

  - alert: KubernetesNodeHighMemory
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Kubernetes node has high memory usage"
      description: "Kubernetes node {{ $labels.instance }} memory usage is above 80% for more than 5 minutes."

  - alert: KubernetesNodeDiskSpaceLow
    expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Kubernetes node has low disk space"
      description: "Kubernetes node {{ $labels.instance }} disk usage is above 80% for more than 5 minutes."

  # Kubernetes Pods
  - alert: KubernetesPodCrashLooping
    expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Kubernetes pod is crash looping"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping."

  - alert: KubernetesPodNotReady
    expr: kube_pod_status_phase{phase!="Running",phase!="Succeeded"} > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Kubernetes pod is not ready"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not ready."

  # Kubernetes Deployments
  - alert: KubernetesDeploymentReplicasMismatch
    expr: kube_deployment_status_replicas_available != kube_deployment_spec_replicas
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Kubernetes deployment replicas mismatch"
      description: "Deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has {{ $value }} available replicas but {{ $labels.replicas }} desired."

  # Kubernetes Services
  - alert: KubernetesServiceDown
    expr: up{job="kubernetes-services"} == 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Kubernetes service is down"
      description: "Service {{ $labels.kubernetes_name }} in namespace {{ $labels.kubernetes_namespace }} is down."
