# Web Application Security Policies
# This demonstrates comprehensive security policies for web applications

apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: web-app-security
  namespace: default
spec:
  # Select web application pods
  selector: app == "web-app"
  
  types:
  - Ingress
  - Egress
  
  ingress:
  # Allow HTTP/HTTPS from ingress controller
  - action: Allow
    protocol: TCP
    source:
      selector: app == "ingress-controller"
    destination:
      ports:
      - 80
      - 443
  
  # Allow health checks
  - action: Allow
    protocol: TCP
    source:
      selector: app == "health-checker"
    destination:
      ports:
      - 8080
  
  # Allow monitoring
  - action: Allow
    protocol: TCP
    source:
      selector: app == "prometheus"
    destination:
      ports:
      - 9090
  
  egress:
  # Allow database connections
  - action: Allow
    protocol: TCP
    destination:
      selector: app == "database"
      ports:
      - 5432
  
  # Allow Redis connections
  - action: Allow
    protocol: TCP
    destination:
      selector: app == "redis"
      ports:
      - 6379
  
  # Allow DNS
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53
  
  # Allow HTTPS to external services
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 443
---
# Database Security Policy
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: database-security
  namespace: default
spec:
  selector: app == "database"
  
  types:
  - Ingress
  - Egress
  
  ingress:
  # Only allow connections from web apps
  - action: Allow
    protocol: TCP
    source:
      selector: app == "web-app"
    destination:
      ports:
      - 5432
  
  # Allow backup connections
  - action: Allow
    protocol: TCP
    source:
      selector: app == "backup-service"
    destination:
      ports:
      - 5432
  
  egress:
  # Allow DNS
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53
  
  # Deny all other egress
  - action: Deny
