version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-web-app
    ports:
      - "8080:8080"   # host:container
    environment:
      GIN_MODE: "release"   # example env var if you use Gin
    volumes:
      - appdata:/app/data   # if your app writes data i.e SQL/Logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  appdata:
