apiVersion: v1
kind: ConfigMap
metadata:
  name: python-config
  labels:
    app: python-app
    component: config
data:
  # Application Configuration
  FLASK_ENV: "production"
  FLASK_DEBUG: "false"
  LOG_LEVEL: "INFO"
  
  # Database Configuration
  DB_POOL_SIZE: "10"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"
  
  # Redis Configuration
  REDIS_POOL_SIZE: "10"
  REDIS_TIMEOUT: "5"
  
  # Application Settings
  MAX_CONTENT_LENGTH: "16777216"  # 16MB
  PERMANENT_SESSION_LIFETIME: "3600"  # 1 hour
  
  # Security Settings
  SECRET_KEY: "your-secret-key-here"
  WTF_CSRF_ENABLED: "true"
  WTF_CSRF_TIME_LIMIT: "3600"
  
  # Monitoring Configuration
  ENABLE_METRICS: "true"
  METRICS_PORT: "5000"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Caching Configuration
  CACHE_TYPE: "simple"
  CACHE_DEFAULT_TIMEOUT: "300"
  
  # Email Configuration (if needed)
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USE_TLS: "true"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  
  # File Upload Configuration
  UPLOAD_FOLDER: "/app/uploads"
  MAX_FILE_SIZE: "10485760"  # 10MB
  ALLOWED_EXTENSIONS: "txt,pdf,png,jpg,jpeg,gif"
  
  # API Configuration
  API_RATE_LIMIT: "100"
  API_RATE_LIMIT_WINDOW: "60"
  
  # Logging Configuration
  LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  LOG_FILE: "/app/logs/app.log"
  LOG_MAX_SIZE: "10485760"  # 10MB
  LOG_BACKUP_COUNT: "5"
  
  # Performance Configuration
  WORKER_THREADS: "4"
  WORKER_CONNECTIONS: "1000"
  KEEPALIVE_TIMEOUT: "65"
  
  # Feature Flags
  ENABLE_DEBUG_ENDPOINTS: "false"
  ENABLE_PROFILING: "false"
  ENABLE_CORS: "true"
  
  # External Services
  EXTERNAL_API_URL: "https://api.example.com"
  EXTERNAL_API_TIMEOUT: "30"
  
  # Application-specific settings
  APP_NAME: "Python K8s App"
  APP_VERSION: "1.0.0"
  APP_DESCRIPTION: "Python application running on Kubernetes"
  
  # Timezone Configuration
  TZ: "UTC"
  
  # Python-specific settings
  PYTHONPATH: "/app"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  
  # Gunicorn Configuration (if using Gunicorn)
  GUNICORN_WORKERS: "4"
  GUNICORN_WORKER_CLASS: "sync"
  GUNICORN_WORKER_CONNECTIONS: "1000"
  GUNICORN_MAX_REQUESTS: "1000"
  GUNICORN_MAX_REQUESTS_JITTER: "100"
  GUNICORN_TIMEOUT: "30"
  GUNICORN_KEEPALIVE: "2"
  GUNICORN_PRELOAD_APP: "true"
  
  # Health Check Configuration
  HEALTH_CHECK_PATH: "/health"
  READINESS_CHECK_PATH: "/ready"
  LIVENESS_CHECK_PATH: "/health"
  
  # Graceful Shutdown Configuration
  GRACEFUL_SHUTDOWN_TIMEOUT: "30"
  SHUTDOWN_HANDLERS_ENABLED: "true"
