apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: conditional-
  annotations:
    description: "Demonstrates conditional logic in Argo Workflows"
spec:
  entrypoint: conditional-demo
  arguments:
    parameters:
    - name: should-run
      value: "true"
    - name: environment
      value: "production"
  templates:
  - name: conditional-demo
    steps:
    - - name: check-condition
        template: condition-check
    - - name: run-if-true
        template: whalesay
        when: "{{steps.check-condition.outputs.result}} == true"
    - - name: run-if-production
        template: production-task
        when: "{{workflow.parameters.environment}} == production"
  - name: condition-check
    script:
      image: alpine:3.18
      command: [sh]
      source: |
        if [ "{{workflow.parameters.should-run}}" = "true" ]; then
          echo "true"
        else
          echo "false"
        fi
      resources:
        requests:
          memory: "32Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "200m"
  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["Condition was true! Running task..."]
      resources:
        requests:
          memory: "32Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "200m"
  - name: production-task
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["Running in production environment!"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "200m"
