# Calico Installation Configuration
# This configures Calico networking using Tigera Operator

apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Calico networking configuration
  calicoNetwork:
    # IP pool configuration
    ipPools:
    - blockSize: 26
      cidr: 192.168.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: ""
    
    # BGP configuration
    bgp: Disabled
    
    # Node address selection
    nodeAddressAutodetectionV4:
      firstFound: true
  
  # CNI configuration
  cni:
    type: Calico
  
  # FlexVolume driver path
  flexVolumePath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
  
  # Node update strategy
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  
  # Service account configuration
  serviceAccountName: calico-node
  
  # Typha configuration (for large clusters)
  typhaMetricsPort: 9093
  
  # Calico node configuration
  calicoNodeDaemonSet:
    spec:
      template:
        spec:
          containers:
          - name: calico-node
            resources:
              requests:
                cpu: 250m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 500Mi
---
# Calico API server configuration
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
