version: '3.8'

services:
  # cAdvisor for container monitoring
  cadvisor:
    image: cleanstart/cadvisor:latest
    container_name: cadvisor-basic
    restart: unless-stopped
    ports:
      - "8085:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Test container to monitor
  test-app:
    image: nginx:alpine
    container_name: test-app-basic
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CPU-intensive test container
  cpu-test:
    image: busybox:latest
    container_name: cpu-test-basic
    command: ["sh", "-c", "while true; do echo 'CPU test running...'; sleep 1; done"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ps", "aux"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Memory-intensive test container
  memory-test:
    image: python:3.9-alpine
    container_name: memory-test-basic
    command: ["python", "-c", "import time; data = []; [data.append('x' * 1024 * 1024) for _ in range(100)]; time.sleep(3600)"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ps", "aux"]
      interval: 30s
      timeout: 10s
      retries: 3
