version: '3.8'

services:
  # Prometheus
  prometheus:
    image: cleanstart/prometheus:latest
    container_name: prometheus-simple
    user: "65534:65534"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.external-url=http://localhost:9090'
      - '--query.max-concurrency=20'
      - '--query.max-samples=50000000'
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  # Node Exporter
  node-exporter:
    image: cleanstart/node-exporter:latest
    container_name: node-exporter-simple
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    privileged: true
    restart: unless-stopped

volumes:
  prometheus_data:
    driver: local
