apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: minio-operator
  labels:
    app: minio-operator
    component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-operator
  template:
    metadata:
      labels:
        app: minio-operator
        component: operator
    spec:
      serviceAccountName: minio-operator
      containers:
      - name: minio-operator
        image: minio/operator:v5.0.6
        ports:
        - containerPort: 4222
          name: http
        - containerPort: 4223
          name: https
        env:
        - name: WATCHED_NAMESPACE
          value: ""
        - name: MINIO_OPERATOR_IMAGE
          value: "minio/operator:v5.0.6"
        - name: MINIO_IMAGE
          value: "minio/minio:RELEASE.2024-01-16T16-07-38Z"
        - name: MINIO_CONSOLE_IMAGE
          value: "minio/console:v0.22.0"
        - name: MINIO_MCS_IMAGE
          value: "minio/mcs:latest"
        - name: MINIO_KES_IMAGE
          value: "minio/kes:v0.25.0"
        - name: MINIO_PROMETHEUS_IMAGE
          value: "minio/prometheus:latest"
        - name: MINIO_LOGGER_IMAGE
          value: "minio/logger:latest"
        - name: MINIO_OPERATOR_LOG_LEVEL
          value: "info"
        - name: MINIO_OPERATOR_WATCH_NAMESPACE
          value: ""
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4222
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 4222
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
