apiVersion: v1
kind: ServiceMonitor
metadata:
  name: minio-tenant-monitor
  namespace: minio-operator
  labels:
    app: minio
    component: monitoring
spec:
  selector:
    matchLabels:
      app: minio
      component: prometheus
  endpoints:
  - port: prometheus
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: minio-operator-monitor
  namespace: minio-operator
  labels:
    app: minio-operator
    component: monitoring
spec:
  selector:
    matchLabels:
      app: minio-operator
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-monitoring-config
  namespace: minio-operator
  labels:
    app: minio
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "minio_rules.yml"
    
    scrape_configs:
    - job_name: 'minio-tenant'
      static_configs:
      - targets: ['minio-tenant-prometheus:9090']
      scrape_interval: 30s
      metrics_path: /metrics
    
    - job_name: 'minio-operator'
      static_configs:
      - targets: ['minio-operator:4222']
      scrape_interval: 30s
      metrics_path: /metrics
    
    - job_name: 'minio-sidecar'
      static_configs:
      - targets: ['app-with-minio-sidecar:9000']
      scrape_interval: 30s
      metrics_path: /minio/v2/metrics/cluster
  
  minio_rules.yml: |
    groups:
    - name: minio.rules
      rules:
      - alert: MinIODown
        expr: up{job=~"minio.*"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MinIO instance {{ $labels.instance }} is down"
          description: "MinIO instance {{ $labels.instance }} has been down for more than 1 minute."
      
      - alert: MinIOHighCPU
        expr: rate(container_cpu_usage_seconds_total{container="minio"}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MinIO instance {{ $labels.instance }} has high CPU usage"
          description: "MinIO instance {{ $labels.instance }} CPU usage is above 80% for more than 5 minutes."
      
      - alert: MinIOHighMemory
        expr: container_memory_usage_bytes{container="minio"} / container_spec_memory_limit_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MinIO instance {{ $labels.instance }} has high memory usage"
          description: "MinIO instance {{ $labels.instance }} memory usage is above 80% for more than 5 minutes."
      
      - alert: MinIOStorageFull
        expr: minio_disk_usage_percentage > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MinIO instance {{ $labels.instance }} storage is almost full"
          description: "MinIO instance {{ $labels.instance }} storage usage is above 80% for more than 5 minutes."
