apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-sidecar-pvc
  namespace: minio-operator
  labels:
    app: minio-sidecar
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-tenant-pvc
  namespace: minio-operator
  labels:
    app: minio
    component: tenant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
