---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-bgp
  labels:
    app: nginx-bgp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-bgp
  template:
    metadata:
      labels:
        app: nginx-bgp
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-bgp-service
  labels:
    app: nginx-bgp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-bgp
