---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: api-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.246-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: api-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - api-pool
