---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: web-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.245
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: web-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - web-pool
