apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    component: database
type: Opaque
data:
  # Base64 encoded values
  # postgres (password)
  postgres-password: cGFzc3dvcmQ=
  # postgres (username) 
  postgres-user: cG9zdGdyZXM=
  # helloworld (database name)
  postgres-db: aGVsbG93b3JsZA==
