# Stakater Reloader Secret Example
# This demonstrates how to use Stakater Reloader with Secrets

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  annotations:
    # This annotation tells Reloader to restart pods when this Secret changes
    reloader.stakater.com/auto: "true"
type: Opaque
data:
  # Base64 encoded values
  database-password: cGFzc3dvcmQxMjM=  # password123
  api-key: YWJjZGVmZ2hpams=           # abcdefghijk
  jwt-secret: c2VjcmV0a2V5MTIzNDU2Nzg5  # secretkey123456789
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-secrets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-with-secrets
  template:
    metadata:
      labels:
        app: app-with-secrets
      annotations:
        # This annotation tells Reloader to restart pods when Secret changes
        secret.reloader.stakater.com/reload: "app-secrets"
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: api-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: app-secrets
