version: '3.8'

services:
  # PostgreSQL Database using CleanStart
  db:
    image: cleanstart/postgres:latest
    container_name: cleanstart-postgres-db
    environment:
      POSTGRES_DB: helloworld
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      /bin/sh -c "
        mkdir -p /run/postgresql &&
        chown postgres:postgres /run/postgresql &&
        if [ ! -f /var/lib/postgresql/data/PG_VERSION ]; then
          initdb -D /var/lib/postgresql/data;
        fi &&
        postgres -D /var/lib/postgresql/data -k /tmp
      "
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Flask Web Application using standard Python (CleanStart Python has shell issues)
  web:
    build: .
    container_name: cleanstart-postgres-web
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: helloworld
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      FLASK_ENV: production
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
