version: '3.8'

services:
  curl-client:
    image: cleanstart/curl:latest
    container_name: curl-client
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
    environment:
      - API_BASE_URL=https://httpbin.org
      - TEST_MODE=true
    working_dir: /workspace
    command: ["tail", "-f", "/dev/null"]
    profiles:
      - development
      - testing

  curl-interactive:
    image: cleanstart/curl:latest
    container_name: curl-interactive
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
    environment:
      - API_BASE_URL=https://httpbin.org
    working_dir: /workspace
    stdin_open: true
    tty: true
    profiles:
      - interactive

  curl-test-runner:
    image: cleanstart/curl:latest
    container_name: curl-test-runner
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
    environment:
      - API_BASE_URL=https://httpbin.org
      - TEST_MODE=true
    working_dir: /workspace
    command: ["bash", "/workspace/scripts/run-all-tests.sh"]
    profiles:
      - testing

  curl-monitor:
    image: cleanstart/curl:latest
    container_name: curl-monitor
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
    environment:
      - MONITOR_URL=https://httpbin.org/health
      - CHECK_INTERVAL=30
    working_dir: /workspace
    command: ["bash", "-c", "while true; do curl -s -o /dev/null -w '%{http_code}' $MONITOR_URL; echo ' - $(date)'; sleep $CHECK_INTERVAL; done"]
    profiles:
      - monitoring

networks:
  default:
    name: curl-network
